### ISSUE TITLE
[Android Bootcamp] Twitter Client - Review my app

### ISSUE THREAD

**Issue by dpkagrawal** [dpkagrawal/Simple-Twitter-Client#1]
I have been working with Active Android to save tweets to sqlite but didnt get it working properly. So didnt push the code. 

/cc @nesquena @timothy1ee

**Comment by nesquena** [comment]
Deepak, :+1: nice work overall. A few notes after checking out the code:
- Good that you only have a single method which calls getHomeTimeline
- Consider adding the character count for Compose Activity to limit to 140. See [this event handler](https://github.com/thecodepath/android_guides/wiki/Basic-Event-Listeners#textchangedlistener) for more details.
- Good to see you added the tweet after you posted new on compose
- Consider adding ActiveAndroid to the `Tweet` and `User`. See the [persistence guide](https://github.com/thecodepath/android_guides/wiki/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](https://github.com/thecodepath/android_guides/wiki/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 3 Feedback Guide here](https://gist.github.com/nesquena/a41220c54c9550f69599) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, Models, Authentication, API Communication, Preferences, ActionBar, et al) and see how they all fit together. We are close to a turning point in the course where you should be hitting a "critical mass" for your Android knowledge.

**Comment by nesquena** [comment]
> I have been working with Active Android to save tweets to sqlite but didnt get it working properly.

What issue were you having?
