### ISSUE TITLE
 [Android Bootcamp] Twitter Client - Review my app

### ISSUE THREAD

**Issue by dpkagrawal** [dpkagrawal/Simple-Twitter-Client#2]
/cc @nesquena @timothy1ee

**Comment by nesquena** [comment]
Deepak, :+1: nice work overall. A few notes after checking out the code:
- In the future, definitely consider [polishing up the UI ](https://gist.github.com/nesquena/6c567083aec13d868017) by reviewing the [cloning a screen](https://github.com/thecodepath/android_guides/wiki/Cloning-a-Login-Screen-Layout) tutorial and Q&A and the [drawables](https://github.com/thecodepath/android_guides/wiki/Drawables) guide.
- For tabs, try following [this approach](https://github.com/thecodepath/android_guides/wiki/Creating-and-Using-Fragments#without-actionbarsherlock) for cleaner tab listeners and better memory management.
- Nice use of tag to setup the ability to click the profile image and view a user's profile
- For a future exercise, challenge yourself to move even more of the logic into the base Fragment class and out of the extension timeline fragments. For example, the scroll listener could be set in the base class and then the "onLoadMore" could call an abstract method which is defined separately in the extended class.

Here's a detailed [Project 4 Feedback Guide here](https://gist.github.com/nesquena/d88cf3606a308359323f) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission. 

This week (Week 5), we are going to cover the last major piece to the Android puzzle and that is using the hardware and SDK components such as the camera, photo gallery, location, maps, etc. After that, Week 6 we will be covering all the topics that separate an intermediate Android developer from a beginner that will act things you should start reviewing to continue your path to being a great Android developer.

Week 7 (Nov 11th), we are going to have a demo day to celebrate the progress you've all made with our next batch of Android students and multiple companies attending to see the group projects that you all have built. We are going to help however we can over the next 2 weeks to get the apps in shape and also have you all prepare a short slide presentation as well.
